# Define the installation directory and vimrc.local file path
DESTDIR :=
INSTALL_DIR := /opt/aat-vimrc
VIMRC_DIR := /etc/vim
VIMRC_FILE := vimrc.local

# Define the list of directories and files to install
INSTALL_ITEMS = autoload \
                LICENSE \
                README.md \
                sources_forked \
                sources_non_forked \
                temp_dirs \
                update_plugins.sh \
                vimrcs

# Default target: install everything
install: $(INSTALL_ITEMS)
	@echo "Installing Awesome Vim configuration from $(DESTDIR)/$(INSTALL_DIR)..."
	mkdir -p $(DESTDIR)/$(INSTALL_DIR) $(DESTDIR)/$(VIMRC_DIR)
	cp -r $(INSTALL_ITEMS) $(DESTDIR)/$(INSTALL_DIR)
	@echo "Setting up Vim configuration in $(DESTDIR)/$(VIMRC_LOCAL)..."
	@printf "%s\n" \
	"\" DO NOT EDIT THIS FILE" \
	"set runtimepath+=$(INSTALL_DIR)" \
	"source $(INSTALL_DIR)/vimrcs/basic.vim" \
	"source $(INSTALL_DIR)/vimrcs/filetypes.vim" \
	"source $(INSTALL_DIR)/vimrcs/plugins_config.vim" \
	"source $(INSTALL_DIR)/vimrcs/extended.vim" \
	> $(DESTDIR)/$(VIMRC_DIR)/$(VIMRC_FILE)
	@echo "Installed the Ultimate Vim configuration successfully! Enjoy!"

# Clean target: remove the installation directory
clean:
	@echo "Cleaning up $(DESTDIR)/$(INSTALL_DIR)..."
	@if [ -d $(DESTDIR)/$(INSTALL_DIR) ]; then \
		rm -rf $(DESTDIR)/$(INSTALL_DIR); \
	else \
		echo "$(DESTDIR)/$(INSTALL_DIR) not found, already cleaned."; \
	fi

# Uninstall target: remove the installation directory and vimrc.local
uninstall:
	@echo "Uninstalling Awesome Vim configuration..."
	@rm -rf $(DESTDIR)/$(INSTALL_DIR)
	@rm -f $(DESTDIR)/$(VIMRC_DIR)/$(VIMRC_FILE)
	@echo "Uninstalled successfully."

# Phony targets to avoid conflicts with directories or files named 'install' or 'clean'
.PHONY: install clean uninstall
