# Define the installation directory and vimrc.local file path
DESTDIR :=
INSTALL_DIR := /opt/amix-vimrc-tweaks
VIMRC_DIR := /etc/vim
VIMRC_FILE := vimrc.local

# Define the list of directories and files to install
INSTALL_ITEMS = autoload \
                LICENSE \
                my_plugins \
                README.md \
                sources_forked \
                sources_non_forked \
                temp_dirs \
                update_plugins.py \
                vimrcs

# Default target: install everything
install: $(INSTALL_ITEMS)
	@echo "Installing Awesome Vim configuration from $(DESTDIR)/$(INSTALL_DIR)..."
	mkdir -p $(DESTDIR)/$(INSTALL_DIR) $(DESTDIR)/$(VIMRC_DIR)
	cp -r $(INSTALL_ITEMS) $(DESTDIR)/$(INSTALL_DIR)
	@echo "Setting up Vim configuration in $(DESTDIR)/$(VIMRC_LOCAL)..."
	@printf "%s\n" \
	"\" DO NOT EDIT THIS FILE" \
	"\" Add your own customizations in $(INSTALL_DIR)/my_configs.vim" \
	"set runtimepath+=$(INSTALL_DIR)" \
	"source $(INSTALL_DIR)/vimrcs/basic.vim" \
	"source $(INSTALL_DIR)/vimrcs/filetypes.vim" \
	"source $(INSTALL_DIR)/vimrcs/plugins_config.vim" \
	"source $(INSTALL_DIR)/vimrcs/extended.vim" \
	"try" \
	"  source $(INSTALL_DIR)/my_configs.vim" \
	"catch" \
	"endtry" \
	> $(DESTDIR)/$(VIMRC_DIR)/$(VIMRC_FILE)
	@chmod -R 777 $(DESTDIR)/$(INSTALL_DIR)/my_plugins
	@echo "Installed the Ultimate Vim configuration successfully! Enjoy!"

# Clean target: remove the installation directory, but preserve my_plugins and my_configs.vim
clean:
	@echo "Cleaning up $(DESTDIR)/$(INSTALL_DIR) but preserving my_plugins and my_configs.vim..."
	@if [ -d $(DESTDIR)/$(INSTALL_DIR) ]; then \
		find $(DESTDIR)/$(INSTALL_DIR) -mindepth 1 ! -name 'my_plugins' ! -name 'my_configs.vim' -exec rm -rf {} +; \
	else \
		echo "$(DESTDIR)/$(INSTALL_DIR) not found, already cleaned."; \
	fi

# Phony targets to avoid conflicts with directories or files named 'install' or 'clean'
.PHONY: install clean
